[default]
SQLALCHEMY_DATABASE_URI = "sqlite:///database/weversousa.db"
SQLALCHEMY_TRACK_MODIFICATIONS = false
TITLE = "Brasileirao"
SECRET_KEY = "abobrinha"
EXTENSIONS = [
    "brasileirao.database",
    "brasileirao.views",
    "brasileirao.cli",
]

[production]
